on: push

jobs:
  use_s3cmd:
    runs-on: ubuntu-latest
    name: Validate Project
    steps:
      - name: check if index.js is in diff
        run: git diff
      - name: Build and compare dist
        run: |
          mv dist/index.js old
          npm run build
          if cmp --silent -- old dist/index.js; then
            exit 0
          else
            exit 1
          fi
      